### PR TITLE
Package selection argument guardrails

### PR DESCRIPTION
**Pull request by rotu**
1. If no package names provided to --packages-select / --packages-skip / --packages-select-regex / --packages-skip-regex, fail with an error like `colcon test: error: argument --packages-select: expected at least one argument`
2. Compile regexes when processing arguments
3. Validate that package names don't start with '-', to avoid ambiguity with arguments. These will fail with an error like `colcon test: error: argument --packages-select: invalid package_name value: '-foo'`

fix https://github.com/colcon/colcon-core/issues/325

### CODE REVIEW

**Comment by dirk-thomas** [comment]
I am not sure if this restriction is a good idea. There is no rule that a name can't start with a `-` (that is only restricted for ROS package names).

**Comment by dirk-thomas** [comment]
Please split the regex refactoring into a separate PR to allow iterating on the separate changes independently. Also the change from `*` to `+` seems unrelated (and imo undesired).

**Comment by rotu** [comment]
I think it's a categorically bad idea to name a package starting with a hyphen and it's a reasonable restriction. There's already a de-facto restriction that package names can't overlap any colcon command line options or else argparse will *always* treat them as package names.

The cmake package identification extension seems to already restrict packages to names consisting of letters, numbers, hyphen, and underscore, even though *all* strings seem to be acceptable project names, including ones with spaces..

Python packages starting with hyphens already fail.

**Comment by rotu** [comment]
Why do you think * -> + is a bad idea? It seems like omitting package names after that argument is a probable mistake

**Comment by dirk-thomas** [comment]
> I think it's a categorically bad idea to name a package starting with a hyphen it's a reasonable restriction.

My point is that in order to enforce this restriction it first needs to be clearly stated and defined explicitly what is allowed and what is not. And it needs to be ensured that it isn't more restrictive than any build tool we might want to support in the future with `colcon`.

> The cmake package identification extension seems to already restrict packages to names consisting of letters, numbers, hyphen, and underscore, even though all strings seem to be acceptable project names, including ones with spaces..

I am pretty sure that restrictions comes from CMake itself and isn't something `colcon-cmake` just came up with out of the blue.

> Why do you think * -> + is a bad idea?

Because I can e.g. invoke the command with the arguments coming from a second invocation of `colcon list ...` and may simply be empty.

> Python packages starting with hyphens already fail.

Each language / tool will likely have its own restrictions. And `colcon` can follow those - for packages of that type. It just shouldn't enforce a restriction which maybe in the future we want to add support X and it allows names of X-packages to start with `-`.

**Comment by rotu** [comment]
I believe pretty strongly in these changes, and they make my life easier. Closing PR, as I don't feel like picking it apart. Feel free to pull any changes from my project fork.

**Comment by dirk-thomas** [comment]
> Closing PR, as I don't feel like picking it apart. Feel free to pull any changes from my project fork.

Sorry to hear that. If you don't think a few minutes to do so are worth your time please don't expect others to do it for you.

**Pull request closed without merging**
